#! /bin/sh

# --
#
PROJECT="YACS"

# --
# set VERSION from CVS_TAG_NAME

CVS_TAG_NAME='$Name$'
VERSION=${CVS_TAG_NAME}
VERSION=`echo ${VERSION/'$Name:'/}`
VERSION=`echo ${VERSION/'$'/}`
if test X$VERSION = X ; then
    VERSION=`date +"%F"`   # -%H-%M
else
    VERSION=`echo $VERSION | sed -e "s/V_//g"`
    VERSION=`echo $VERSION | sed -e "s/_/./g"`
fi

# --
ORIG_DIR=`pwd`
run() {
    local logfile=$ORIG_DIR/build_configure.log
    printf "%-50s" "$1 ... "
    eval $1 > $logfile 2>&1
    if test $? != 0 ; then
        echo "[FAILED]"
        echo "see file build_configure.log ..."
        exit 1
    fi
    echo "[  OK  ]"
}

# --
# -- goto build_configure dir
CONF_DIR=`echo $0 | sed -e "s,[^/]*$,,;s,/$,,;s,^$,.,"`
cd ${CONF_DIR}

# --
# -- list all Makefile.am in Makefile.am.list
./rfind . Makefile.am > Makefile.am.list

# --
# -- configure.in construction
rm -f configure.in
touch configure.in
#echo "AC_INIT(src)" >> configure.in
echo "AC_INIT(YACS,0.1)" >> configure.in
echo "RELEASE=$VERSION" >> configure.in
echo "PROJECT=$PROJECT" >> configure.in
cat configure.in.base >> configure.in
echo "AC_OUTPUT([ \\" >> configure.in
# echo "  src/XDATA/xversion.py \\" >> configure.in
# echo "  doc/xversion.tex \\" >> configure.in
sed -e 's,\.am, \\,' -e 's,\.\/,,' Makefile.am.list >> configure.in
echo  "])" >> configure.in

# --
run "libtoolize"
run "aclocal -I adm/unix/config_files"
run "autoconf"
run "automake --add-missing --copy"
