#! /bin/sh

# --
# --
ORIG_DIR=`pwd`
run() {
    local logfile=$ORIG_DIR/build_configure.log
    printf "%-50s" "$1 ... "
    eval $1 > $logfile 2>&1
    if test $? != 0 ; then
        echo "[FAILED]"
        echo "see file build_configure.log ..."
        exit 1
    fi
    echo "[  OK  ]"
}

# --
# -- goto build_configure dir
CONF_DIR=`echo $0 | sed -e "s,[^/]*$,,;s,/$,,;s,^$,.,"`
cd ${CONF_DIR}

# --
# -- configure.in construction
rm -f configure.in
touch configure.in

cat configure.in.base >> configure.in

# --

run "libtoolize --force --copy --automake"
run "aclocal -I adm/unix/config_files"
run "autoheader -I adm/unix/config_files"
run "autoconf"
run "automake --add-missing --copy"
