#! /bin/sh

# --
#
PROJECT="salome"
VERSION=4.0.0
XVERSION=0x040000
MODULE_NAME="yacsgui"

# --
ORIG_DIR=`pwd`
run() {
    local logfile=$ORIG_DIR/build_configure.log
    printf "%-50s" "$1 ... "
    eval $1 > $logfile 2>&1
    if test $? != 0 ; then
        echo "[FAILED]"
        echo "see file build_configure.log ..."
        exit 1
    fi
    echo "[  OK  ]"
}

# --
# -- goto build_configure dir
CONF_DIR=`echo $0 | sed -e "s,[^/]*$,,;s,/$,,;s,^$,.,"`
cd ${CONF_DIR}

# --
# -- list all Makefile.am in Makefile.am.list
./rfind . Makefile.am > Makefile.am.list

# --
# -- configure.in construction
rm -f configure.in
touch configure.in
#echo "AC_INIT(src)" >> configure.in
echo "AC_INIT($PROJECT,$VERSION)" >> configure.in
echo "RELEASE=$VERSION" >> configure.in
echo "PROJECT=$PROJECT" >> configure.in
echo "PACKAGE=$PROJECT" >> configure.in
echo "MODULE_NAME=$MODULE_NAME" >> configure.in

cat configure.in.base >> configure.in

echo "AC_OUTPUT([ \\" >> configure.in

sed -e 's,\.am, \\,' -e 's,\.\/,,' Makefile.am.list >> configure.in

echo "    src/yacsloader/Test/YacsLoaderTest.sh \\" >> configure.in
echo "    src/yacsloader/Test/YacsLoaderInSessionTest.sh \\" >> configure.in
echo "    src/yacsloader/Test/YacsLoaderInSessionTest2.sh \\" >> configure.in
echo "    src/yacsloader/Test/display.sh \\" >> configure.in
echo "    src/yacsloader/Test/config_appli.xml \\" >> configure.in
echo "    src/gui/resources/YACSGuiCatalog.xml \\" >> configure.in
echo "    doc/Doxyfile \\" >> configure.in

echo  "])" >> configure.in

# --

run "libtoolize"
run "aclocal -I adm/unix/config_files"
run "autoheader -I adm/unix/config_files"
run "autoconf"
run "automake --add-missing --copy"
