#!/bin/sh
# Copyright (C) 2006-2013  CEA/DEN, EDF R&D
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
#

CONF_DIR=`echo $0 | sed -e "s,[^/]*$,,;s,/$,,;s,^$,.,"`
cd ${CONF_DIR}

TO_CLEAN=
TO_CLEAN=${TO_CLEAN}' build_configure.log'
TO_CLEAN=${TO_CLEAN}' Makefile.am.list'
TO_CLEAN=${TO_CLEAN}' aclocal.m4'
TO_CLEAN=${TO_CLEAN}' autom4te*'
TO_CLEAN=${TO_CLEAN}' configure'
TO_CLEAN=${TO_CLEAN}' configure.in'
TO_CLEAN=${TO_CLEAN}' yacs_config.h.in'

rm -rf $TO_CLEAN > /dev/null

find . -name "Makefile.in" -exec rm -f {} \;
find . -name "*~" -exec rm -f {} \;
find . -name "semantic.cache" -exec rm {} \;
find . -name "*.pyc" -exec rm {} \;
rm -f src/salomegui_swig/doc.i
( cd adm/unix/config_files && rm -f l*.m4 config.guess config.sub depcomp install-sh ltmain.sh missing py-compile )
