#! /bin/bash

# print the help message ====================================

# test $@="-h" -o -z $@

hh=0

if test "$#" = "0";then
    hh=1
else
    for a in $@; do
	if test "$a" = "-h"; then
	    hh=1
	fi
    done
fi

if test "$hh" = "1" ; then
    echo ""
    echo "Usage : "
    echo ""
    echo "   to run IDLparser:"
    echo ""
    echo "        $0 -Wbcatalog=<my_catalog.xml>[,icon=<pngfile>][,version=<num>][,author=<name>][,name=<component_name>][,multistudy=<component_multistudy>][,remove=component_name] <file.idl>   "
    echo ""
    echo "   to have omniidl help:"
    echo ""
    echo "        $0 -u "
    echo ""
    exit 1
fi
#============================================================

# environment ==============================================


DIR=`pwd`
EXEC_DIR=`echo $0 | sed -e "s,[^/]*$,,;s,/$,,;s,^$,.,"`
cd $EXEC_DIR/..
SALOME_HOME_DIR=`pwd`
cd $EXEC_DIR

export SALOME_HOME_DIR      
export SALOME_SRC_DIR=/dn05/salome/apv/WORK/SOURCE/KERNEL
export ORB_HOME_DIR=/dn05/salome/ref/PRODUCTS/IW/omniORB-3.0.5

export LD_LIBRARY_PATH=${SALOME_HOME_DIR}/lib:${LD_LIBRARY_PATH}

# echo $SALOME_HOME_DIR = SALOME_HOME_DIR
# echo $SALOME_SRC_DIR = SALOME_SRC_DIR

PYVTK_PATH=
export PYTHONPATH=${PYTHONPATH}:${SALOME_HOME_DIR}/idl:${SALOME_HOME_DIR}/bin:${SALOME_HOME_DIR}/lib:${PYVTK_PATH}:${EXEC_DIR}

MICORC=/dev/null
export MICORC


cd $DIR

PYTHONPATH=${PYTHONPATH}:${SALOME_HOME_DIR}/bin
#============================================================

# omiidl ====================================================
omniidl -bIDLparser -I ${SALOME_SRC_DIR}/idl $@
#============================================================
